# Generated by Django 6.0.2 on 2026-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sections',
            name='text',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
