# Generated by Django 6.0.2 on 2026-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0002_article_description_sections_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sections',
            name='end',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
