# Generated by Django 6.0.2 on 2026-03-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0003_sections_end'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sections',
            name='end',
        ),
        migrations.AlterField(
            model_name='article',
            name='section',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='Wiki.sections'),
        ),
    ]
