# Generated by Django 6.0.2 on 2026-03-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0004_remove_sections_end_alter_article_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='short_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
