# Generated by Django 6.0.2 on 2026-04-05 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0006_remove_article_section_sections_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='Wiki.article'),
        ),
    ]
