# Generated by Django 6.0.2 on 2026-04-25 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0007_alter_sections_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('order', models.IntegerField(unique=True)),
                ('description', models.TextField()),
                ('short_description', models.TextField(blank=True, default=None, null=True)),
                ('main_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Wiki.image')),
            ],
        ),
    ]
