# Generated by Django 6.0.2 on 2026-05-17 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Wiki', '0009_article_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='order',
        ),
        migrations.RemoveField(
            model_name='articleform',
            name='order',
        ),
    ]
